Media_Portal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Movies import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    #movies/
    url(r'^movies/',include('Movies.urls')),

    #register/
    url(r'^register/$',views.register,name="register"),
    #logged_in/
    url(r'^logged_in/$',views.logged_in,name="logged_in"),

    url(r'^logged_out/$',views.log_out,name="log_out"),

    url(r'^search/$',views.search_movie,name="search"),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns+= static(settings.MOVIE_URL, document_root= settings.MOVIE_ROOT)

Movies/urls.py
from django.conf.urls import url
from Movies import views, api
from rest_framework.urlpatterns import format_suffix_patterns

app_name='Movies'

urlpatterns = [
    #movies/<movie_id>
    url(r'^(?P<movie_id>[0-9]+)/$',views.detail,name="detail"),
    #movies/<movie_id>/play/
    url(r'^(?P<movie_id>[0-9]+)/play/$',views.Play_movie,name="play"),
    #movies/<movie_id>/watched/
    url(r'^(?P<movie_id>[0-9]+)/watched/$',views.Watched,name="watched"),
    #movies/<movie_id>/watched/
    url(r'^(?P<movie_id>[0-9]+)/watched/stay=True$',views.Watched_stay,name="watched_stay"),
    #movies/api/name=<name>
    url(r'^api/name=(?P<name>[A-Z,a-z," ",""]+|)?&y=(?P<year>[0-9]+|)$',api.API_res,name="api"),
]

Movies/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import shelve

class Movie(models.Model):
    Name=models.CharField(max_length=300)
    Year=models.CharField(max_length=5)
    Plot=models.CharField(max_length=1500)
    Genre=models.CharField(max_length=250)
    Imdb_rating=models.FloatField(default=0.0)
    Plot_outline=models.CharField(max_length=1000,default=None)
    Director=models.CharField(max_length=50,default=None)
    Poster=models.FileField()
    Path=models.CharField(max_length=100)
    trailer=models.CharField(max_length=150,default=None,null=True,blank=True)

    def __str__(self):
        return self.Name


class Ratings(models.Model):
    Rating = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(5),MinValueValidator(0)])
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    Movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return self.Rating
        

Movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from .models import Movie
from bs4 import BeautifulSoup
import threading
import urllib
import os
import re

def get_youtube_link(movie):
    query = urllib.quote_plus(movie.Name)
    f = urllib.urlopen('https://www.youtube.com/results?search_query='+query+'+trailer').read()
    soup=BeautifulSoup(f,'lxml')
    item = soup.find_all('ol',{'class':'item-section'})
    for itm in item:
        a = item[0].find_all('a',{'class':'yt-uix-sessionlink'})[0]
    a = re.findall('=(.*)',a.get('href'))
    print (a)
    link= 'http://www.youtube.com/embed/'+a[0]
    movie.trailer=link
    movie.save()

def index(request):
    if 'user' in request.session:

        movies_list=Movie.objects.all()
        page = request.GET.get('page', 1)

        paginator = Paginator(movies_list, 12) #the movie size that will display in the index page of each
        try:
            movies = paginator.page(page)
        except PageNotAnInteger:
            movies = paginator.page(1)
        except EmptyPage:
            movies = paginator.page(paginator.num_pages)

        return render(request,'main.html',{'movies':movies})
    return render(request,'login.html')

def logged_in(request):
    if 'user' in request.session and request.user.is_authenticated:
        movies_list=Movie.objects.all()
        page = request.GET.get('page', 1)

        paginator = Paginator(movies_list, 12) #the movie size that will display in the index page of each
        try:
            movies = paginator.page(page)
        except PageNotAnInteger:
            movies = paginator.page(1)
        except EmptyPage:
            movies = paginator.page(paginator.num_pages)

        return render(request,'main.html',{'movies':movies})
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        if not User.objects.filter(username=username).exists():
            return render(request,'login.html',{'error_message':'Please Register First'})
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                request.session['user']=username

                movies_list=Movie.objects.all()
                page = request.GET.get('page', 1)

                paginator = Paginator(movies_list, 12) #the movie size that will display in the index page of each
                try:
                    movies = paginator.page(page)
                except PageNotAnInteger:
                    movies = paginator.page(1)
                except EmptyPage:
                    movies = paginator.page(paginator.num_pages)

                return render(request,'main.html',{'movies':movies})

            else:
                return render(request,'login.html',{'error_message':'Your Account Has Been Suspended'})
        return render(request,'login.html',{'error_message':'Wrong Credentials'})
    return render(request,'login.html')

def register(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        rep_password=request.POST['rep_password']
        e_mail=request.POST['email']
        if User.objects.filter(email=e_mail).exists():
            return render(request,'register.html',{'error_message':'E-mail already registered'})
        elif User.objects.filter(username=username).exists():
            return render(request,'register.html',{'error_message':'Username not available'})
        elif(password!=rep_password):
            return render(request,'register.html',{'error_message':'Passwords Dont match'})
        else:
            user=User(username=username,email=e_mail)
            user.set_password(password)
            user.save()
            user=authenticate(username=username,password=password)
            login(request,user)
            request.session['user']=username
            movies_list=Movie.objects.all()
            page = request.GET.get('page', 1)

            paginator = Paginator(movies_list, 12) #the movie size that will display in the index page of each
            try:
                movies = paginator.page(page)
            except PageNotAnInteger:
                movies = paginator.page(1)
            except EmptyPage:
                movies = paginator.page(paginator.num_pages)

        return render(request,'main.html',{'movies':movies})
    return render(request,'register.html')


def log_out(request):
    if 'user' in request.session:
        del request.session['user']
        logout(request)
        return redirect('logged_in')

def detail(request,movie_id):
    if not request.user.is_authenticated:
        return redirect('logged_in')
    threadobj= threading.Thread(target=get_youtube_link,args=[])
    movie=get_object_or_404(Movie,id=movie_id)    
    print (movie.trailer)
    if not movie.trailer:
        try:
            get_youtube_link(movie)
        except:
            pass
    return render(request,'details.html',{'movie':movie})

def search_movie(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            if not request.POST['search']:
                return redirect('logged_in')
            if '-w' in request.POST['search']:
                Q=re.findall('(.*)\s+-w',request.POST['search'])
                if not Q:
                    movies_list=Movie.objects.filter(Watched=False)
                    page = request.GET.get('page', 1)

                    paginator = Paginator(movies_list, 12) #the movie size that will display in the index page of each
                    try:
                        movies = paginator.page(page)
                    except PageNotAnInteger:
                        movies = paginator.page(1)
                    except EmptyPage:
                        movies = paginator.page(paginator.num_pages)

                    return render(request,'main.html',{'movies':movies})
                else:
                    Q=Q[0]
                    list1=Movie.objects.filter(Name__contains=Q,Watched=False)
                    list2=Movie.objects.filter(Year__contains=Q,Watched=False)
                    list3=Movie.objects.filter(Genre__contains=Q,Watched=False)
            else:
                Q=request.POST['search']
                list1=Movie.objects.filter(Name__contains=Q)
                list2=Movie.objects.filter(Year__contains=Q)
                list3=Movie.objects.filter(Genre__contains=Q)
            res=list(set(list1)^set(list2)^set(list3))
            context={
                'movies':res,
            }
            return render(request,'main.html',context)
    return redirect('logged_in')
    
def Play_movie(request,movie_id):
    if request.user.is_authenticated:
        movie=get_object_or_404(Movie,id=movie_id)
        os.startfile(movie.Path)
        return render(request,'details.html',{'movie':movie})
    return redirect('logged_in')

def Watched(request,movie_id):
    if request.user.is_authenticated:
        movie=get_object_or_404(Movie,id=movie_id)
        if movie.Watched:
            movie.Watched=False
        else:
            movie.Watched=True
        movie.save()
    return redirect('logged_in')

def Watched_stay(request,movie_id):
    if request.user.is_authenticated:
        movie=get_object_or_404(Movie,id=movie_id)
        if movie.Watched:
            movie.Watched=False
        else:
            movie.Watched=True
        movie.save()
        return render(request,'details.html',{'movie':movie})
    return redirect('logged_in')

Movies/templates/base.html
<!doctype html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <title>{% block title %}ethio -movie-porta{% endblock %}</title>
</head>
{% load static %}
<link rel="stylesheet" href="{% static 'css/Bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

<body>
<div class="fix" style="background-image: url({% static 'img/login.jpg' %});">
<nav class="navbar navbar-default navbar-inverse" role="navigation" style="margin-bottom: 0; background-color: #2F4F4F;" >
  <div class="container-fluid" >

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'logged_in' %}"><span class="  glyphicon glyphicon-home"></span>foo</a>
    </div>

    <div class="collapse navbar-collapse" id="topNavBar">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'logged_in' %}">
            <span class="glyphicon glyphicon-cd" area-hidden="true"></span>
            Movies
          </a>
        </li>
      </ul>

    <form class="navbar-form navbar-right" action="{% url 'search' %}" method="post" role="search">
      {% csrf_token %}
      <div class="form-group">
        <input type="text" class="form-control" name="search" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Search</button>



    </form>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="{% url 'log_out' %}">
          <span class="glyphicon glyphicon-off" area-hidden="true"></span>
          Logout
        </a>
      </li>
    </ul>

    </div>
  </div>
</nav>
</div>
{% block body %}
{% endblock %}
</body>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block script %}
{% endblock %}
</html>

Movies/templates/details.html
{% extends 'base.html' %}
{% block title %}{{ movie.Name }}{% endblock %}
{% block body %}

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/Bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />

  <link href="https://vjs.zencdn.net/7.4.1/video-js.css" rel="stylesheet">
  <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  <script src="https://vjs.zencdn.net/ie8/ie8-version/videojs-ie8.min.js"></script>


<div class="container-fluid songs-container" style="background-image: url({% static 'img/bg2.jpg' %});background-repeat:no-repeat; background-size: 100%; position: fixed;">

    <div class="row">
    <br><br><br>
        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'Movies:detail' movie.id %}">
                        {% if movie.Poster %}
                            <img src="{{ movie.Poster.url }}" class="img-responsive">
                        {% else %}
                            <img src="/static/img/no-img.jpg" class="img-responsive">                            
                        {% endif %}
                    </a>
                    <h2>{{ movie.Name }} <small>{{ movie.Year }}</small></h2>
                    <h2>{{ movie.Director }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'index' %}">Back</a></li>
                <li role="presentation" class="active"><a href="{% url 'Movies:watched_stay' movie.id %}">
                  {% if movie.Watched %}
                  Mark Unwatched
                  {% else %}
                  Mark Watched
                  {% endif %}
                </a></li>
                
            </ul>

            <div class="panel panel-default">
                <div class="panel-body" style="background-color: #cccccc; padding-bottom: 70px;">
                    <video id='my-video' class='video-js' controls preload='auto' width='640' height='264'
                      poster='{{ movie.Poster }}' data-setup='{}'>
                      <source src='http://127.0.0.1:7000/{{ movie.Path }}' type="video/mp4">
                      <p class='vjs-no-js'>
                        To view this video please enable JavaScript, and consider upgrading to a web browser that
                        <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
                      </p>
                    </video>
                    <p>the path of the movie: http://127.0.0.1:7000/{{ movie.Path }}</p>
                    <p>the path of the movie: {{MEDIA_URL}}</p>

                    <h5><strong>Watched</strong> :{% if movie.Watched %}Yes{% else %}No{% endif %}</h5>
                    <h5><strong>Year</strong> : {{ movie.Year }}</h5>
                    <h5><strong>IMDB Rating</strong> : {{ movie.Imdb_rating }}</h5>
                    <h5><strong>Genre</strong> : {{ movie.Genre }}</h5>
                    <h5><strong>Plot:</strong></h5>


                    <p>{{ movie.Plot }}</p>


                    {% if movie.trailer %}
                    <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embeded-responsive-item" src="{{movie.trailer}}" frameborder="0" allowfullscreen></iframe>
                    </div>
                    {% else %}
                    <div style="height:480px;width:854;background-color:white;">
                      <div style="margin-top:30px">
                      <img src="/static/img/no.gif"/>
                      <div>
                    </div>
                    {% endif %}
                  </div>

            </div>

        </div>

    </div>

</div>

<script src='https://vjs.zencdn.net/7.4.1/video.js'></script>

{% endblock %}

Movies/templates/login.html
<!doctype html>
<html lang="en" class="no-js">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Media Portal-Log In</title>

	{% load static %}
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/Bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />



</head>

<body>

	<div class="login-page bk-img" style="background-image: url({% static 'img/login.jpg' %});">
		<div class="form-content">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<h1 class="text-center text-bold text-light mt-4x">Log In</h1>
						<div class="well row pt-2x pb-3x bk-light">
							<div class="col-md-8 col-md-offset-2">
								{% if error_message %}
								{{ error_message }}
								{% endif %}
								<form action="{% url 'logged_in' %}" class="mt" method="post">
									{% csrf_token %}
									<label for="username" class="text-uppercase text-sm">Your Username</label>
									<input type="text" placeholder="Username" class="form-control mb" name="username">

									<label for="password" class="text-uppercase text-sm">Password</label>
									<input type="password" placeholder="Password" class="form-control mb" name="password">
									<button class="btn btn-primary btn-block" type="submit">Login</button>
								</form>
								<br>
								<a href="{% url 'register' %}"><button class="btn btn-primary btn-block" type="submit">Sign Up</button></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer">
		<div class="name">
			<div>Copyright &copy; <span>Ethio Movie Portal by foo members</span></div>
	</div>

	<!-- Loading Scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

Movies/templates/main.html
{% extends 'base.html' %}
{% block title %}ethio-movie portal{% endblock %}
{% block body %}

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/Bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />


<div style="width:100%;height:80px">
</div>
<div class="container-fluid" style="background-color: #cccccc; padding-top: 20px;">
    <!-- Albums -->
    {% if movies %}
        {% for movie in movies %}
              {% if forloop.counter|divisibleby:'4' or forloop.counter == 1 %}
                <div class="row">
                     {% endif %}
                    <div class="col-md-3" >
                        <div class="thumbnail" style="background-color: #808080;">
                          <a href="{% url 'Movies:detail' movie.id %}">
                            {% if movie.Poster %}
                             <img src="{{ movie.Poster.url }}" class="img-responsive"  width="275" height="250"
                         style="padding: 10px;margin: 10px;">


                             {% else %}
                             <img src="../static/img/no-poster.png" class="img-responsive"  width="275" height="275"
                         style="padding: 10px;">
                             {% endif %}
                         </a>
                        <div style="vertical-align: top;text-align: left;padding: 10px;background-color: #E6E6FA;">
                            <h3>{{ movie.Name }}</h3>
                            <h4>{{ movie.Year }}</h4>
                             <h5>IMDB Rating : <strong> {{ movie.Imdb_rating }}</strong></h5>
                             <h5><em>{{ movie.Genre }}</em></h5>
                            <!-- View Details -->
                            <a href="{% url 'Movies:detail' movie.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            <!-- Favorite Album -->
                            <a href="{% url 'Movies:watched' movie.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star{% if not movie.Watched %}-empty{% endif %}"></span>
                            </a>

                        </div>
                        </div>
                    </div>

                    {% if forloop.counter|divisibleby:'4' %}
                </div>
                {% endif %}
          {% endfor %}
     {% endif %}
</div>


{% if movies.has_other_pages %}
  <ul class="pagination">
    {% if movies.has_previous %}
      <li><a href="?page={{ movies.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in movies.paginator.page_range %}
      {% if movies.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if movies.has_next %}
      <li><a href="?page={{ movies.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}

Movies/templates/register.html
<!doctype html>
<html lang="en" class="no-js">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Media Portal-Sign In</title>

	{% load static %}
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />



</head>

<body>

	<div class="login-page bk-img" style="background-image: url({% static 'img/login.jpg' %});">
		<div class="form-content">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<h1 class="text-center text-bold text-light mt-4x">Log In</h1>
						<div class="well row pt-2x pb-3x bk-light">
							<div class="col-md-8 col-md-offset-2">
								{% if error_message %}
								{{ error_message }}
								{% endif %}
								<form action="{% url 'register' %}" class="mt" method="post">
                  {% csrf_token %}
									<label for="username" class="text-uppercase text-sm">Username</label>
									<input type="text" placeholder="Username" class="form-control mb" name="username">

									<label for="email" class="text-uppercase text-sm">E-mail</label>
									<input type="text" placeholder="E-mail" class="form-control mb" name="email">

                  <label for="password" class="text-uppercase text-sm">Password</label>
									<input type="password" placeholder="Password" class="form-control mb" name="password">

                  <label for="password" class="text-uppercase text-sm">Password</label>
									<input type="password" placeholder="Password" class="form-control mb" name="rep_password">

									<button class="btn btn-primary btn-block" type="submit">Sign Up</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer">
		<div class="name">
			<div>Copyright &copy; <span>Jeevesh Narang</span></div>
	</div>

	<!-- Loading Scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>